exclude: 'wgo\.player\.css|.*\.pgf'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: "22.6.0"
      hooks:
          - id: black
    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.1
      hooks:
          - id: codespell
            args:
                [
                    "--skip=*.ipynb,*.sgf,*.sgfs,*package-lock.json,*wgo.player.*,sgf-viewer/public/figures/*",
                    "-L=ist",
                ]
    - repo: https://github.com/pycqa/flake8
      rev: "5.0.4"
      hooks:
          - id: flake8
            args: ["--ignore=E501,W503,E302,W605"]
