version: 2.1

executors:
  ubuntu-vm:
    machine:
      # https://discuss.circleci.com/t/linux-machine-executor-update-2022-july-q3-update/44873
      # This image contains Chrome (and seemingly chromedriver), Docker Compose and Python
      image: ubuntu-2204:2024.05.1
      docker_layer_caching: true

commands:
  dependencies:
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum ".circleci/requirements.txt" }}-asjdgklasjdgklasjgh
      - run:
          command: |
            apt update
            DEBIAN_FRONTEND=noninteractive apt install python3.10-venv
            python3.10 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt

      - save_cache:
          key: deps-{{ checksum ".circleci/requirements.txt" }}-asjdgklasjdgklasjgh
          paths:
            - "venv"

jobs:
  build-and-test:
    executor: ubuntu-vm
    steps:
      - dependencies
      - run:
          command: |
            docker build --target streamlit-app -t kata-go-visualizer . \
            && \
            docker run \
              --mount type=bind,source=$READ_DIR,target=$MOUNT_DIR,readonly \
              -e READ_DIR=$READ_DIR \
              -e MOUNT_DIR=$MOUNT_DIR \
              -e PYTHONUNBUFFERED=1 \
              -e PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python \
              --hostname='localhost' \
              -p 8501:8501 \
              -p 6001-6005:6001-6005 \
              -d \
              kata-go-visualizer
          environment:
            READ_DIR: /home/circleci/project/streamlit_app/tests
            MOUNT_DIR: /mnt
      - run:
          command: |
            . venv/bin/activate
            cd /home/circleci/project/streamlit_app/tests
            pytest --reruns 2

  pre-commit-all-files:
    executor: ubuntu-vm
    steps:
      - dependencies
      - run:
          command: |
            . venv/bin/activate
            cp .pre-commit-config.yaml pre-commit-cache-key.txt
            python --version --version >> pre-commit-cache-key.txt
      - restore_cache:
          key: pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run:
          command: |
            . venv/bin/activate
            pre-commit run --all-files
      - save_cache:
          key: pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
            - ~/.cache/pre-commit

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test
      - pre-commit-all-files
