# Launches a container for generating plots.
# Navigate to the *root* of this repo and run:
# docker-compose -f notebooks/docker-compose.yml up

version: "3"

services:
  notebooks:
    image: humancompatibleai/katagovisualizer:notebooks
    build:
      context: ..
      dockerfile: ./notebooks/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /KataGoVisualizer
      - type: bind
        source: /nas/ucb
        target: /nas/ucb
        read_only: true
    cap_add:
      - SYS_PTRACE  # to enable gdb debugging
    tty: true
