# Launches a container for generating plots.
# Navigate to the *root* of this repo and run:
# docker-compose -f notebooks/docker-compose.yml up

version: "3"

services:
  notebooks:
    image: humancompatibleai/katagovisualizer:notebooks
    build:
      context: ..
      dockerfile: ./notebooks/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /KataGoVisualizer
      - type: bind
        source: /nas/ucb
        target: /nas/ucb
        read_only: true
    cap_add:
      - SYS_PTRACE  # to enable gdb debugging
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["1"]
    tty: true
    ports:
      # Host will bind a randomly chosen available port on localhost (127.0.0.1)
      # to the container's port 8888 that Jupyter notebook listens on.
      # To find the port allocated, run `docker ps`.
      - 127.0.0.1::8888
    working_dir: /KataGoVisualizer
    entrypoint: "jupyter-notebook --allow-root --ip=*"
