export const cards: Array<any> =
[
    {
        image: "/images/attack-paper.svg",
        imageName: "Attack paper icon",
        description: "Attack paper",
        url: "https://arxiv.org/abs/2211.00241",
        color: "rgb(0,0,0,0.5)",
        border: false,
    },
    {
        image: "/images/attack-blog.svg",
        imageName: "Attack blog icon",
        description: "Attack blog",
        url: "https://far.ai/post/2023-07-superhuman-go-ais/",
        color: "rgb(70,205,206,0.5)",
        border: false,
    },
    {
        image: "/images/attack-video.svg",
        imageName: "Attack video icon",
        description: "Attack video",
        url: "https://recorder-v3.slideslive.com/#/share?share=83403&s=1a8b2506-2198-4d30-a487-fdb05a497f5f",
        color: "rgb(31,24,42,0.5)",
        border: false,
    },
    {
        image: "/images/financial-times-logo.svg",
        imageName: "Financial Times logo",
        description: "Attack press",
        url: "https://www.ft.com/content/175e5314-a7f7-4741-a786-273219f433a1",
        color: "rgb(252,208,174,0.5)",
        border: false,
    },
    {
        image: "/images/defense-paper.svg",
        imageName: "Defense paper icon",
        description: "Defense paper",
        url: "https://www.overleaf.com/project/654eac3d52dffeb1a092ab18",
        color: "rgb(0,0,0,0.5)",
        border: false,
    },
    {
        image: "/images/defense-blog.svg",
        imageName: "Defense blog icon",
        description: "Defense blog",
        url: "https://far.ai/post/2024-05-go-defense/",
        color: "rgb(70,205,206,0.5)",
        border: false,
    },
    {
        image: "/images/github-mark.svg",
        imageName: "GitHub logo",
        description: "Code",
        url: "https://github.com/AlignmentResearch/go_attack",
        color: "rgb(36,41,46,0.5)",
        border: false,
    },
];
