export const cards: Array<any> =
[
    {
        image: "/images/attack-paper.svg",
        imageName: "Attack paper icon",
        description: "Attack paper",
        url: "https://arxiv.org/abs/2211.00241",
        color: "rgb(252,71,85,0.5)",
        border: false,
    },
    {
        image: "/images/attack-blog.svg",
        imageName: "Attack blog icon",
        description: "Attack blog",
        url: "https://far.ai/post/2023-07-superhuman-go-ais/",
        color: "rgb(252,71,85,0.5)",
        border: false,
    },
    {
        image: "/images/attack-video.svg",
        imageName: "Attack video icon",
        description: "Attack video",
        url: "https://slideslive.com/39006680/adversarial-policies-beat-superhuman-go-ais",
        color: "rgb(252,71,85,0.5)",
        border: false,
    },
    {
        image: "/images/financial-times-logo.svg",
        imageName: "Financial Times logo",
        description: "Attack press",
        url: "https://archive.is/EBcVa",
        color: "rgb(252,208,175,0.5)",
        border: false,
    },
    {
        image: "/images/defense-paper.svg",
        imageName: "Defense paper icon",
        description: "Defense paper",
        url: "https://arxiv.org/abs/2406.12843",
        color: "rgb(79,193,34,0.5)",
        border: false,
    },
    {
        image: "/images/defense-blog.svg",
        imageName: "Defense blog icon",
        description: "Defense blog",
        url: "https://far.ai/post/2024-06-go-defense/",
        color: "rgb(79,193,34,0.5)",
        border: false,
    },
    {
        image: "/images/nature-logo.svg",
        imageName: "Nature logo",
        description: "Defense press",
        url: "https://www.nature.com/articles/d41586-024-02218-7",
        color: "rgb(0,0,0,0.5)",
        border: false,
    },
    {
        image: "/images/github-mark.svg",
        imageName: "GitHub logo",
        description: "Code",
        url: "https://github.com/AlignmentResearch/go_attack",
        color: "rgb(36,40,47,0.5)",
        border: false,
    },
];
